### PR TITLE
display instance-specific login help message, if any

### PR DESCRIPTION
**Pull request by achen2401**
https://www.pivotaltracker.com/story/show/181827732

A message specified in the environment variable, `__KEYCLOAK_LOGIN_INFO_MESSAGE`, will display if the user's login attempt fails.  
The message can be customized per instance. Message for each instance is specified in [this story
](https://www.pivotaltracker.com/story/show/181827732)
Other change:
move in-line styling code to the css file and bump up html body font-size (from 12px to 14px)

### CODE REVIEW

**Comment by achen2401** [comment]
@pbugni  & @ivan-c   Let me know if I am on the right track with this.  I assume that `__KEYCLOAK_LOGIN_INFO_MESSAGE` environment variable will contain the text the Bill has wanted displayed if the user's login attempt fails

**Review by pbugni — APPROVED** [review]
Looks clean - loading the __KEYCLOAK_LOGIN_INFO_MESSAGE value should perhaps land in the appropriate default config file too?

**Comment by achen2401** [comment]
@pbugni I believe that is correct.  I am looking at this [config file](https://github.com/uwcirg/cosri-environments/blob/master/prod/freestanding/femr/keycloak.env.default) .   Perhaps the value for `__KEYCLOAK_LOGIN_INFO_MESSAGE` should land there, i.e. `keycloak.env` on each instance?

**Review by ivan-c — APPROVED** [review]
Looks good, thanks @achen2401 !

**Pull request merged**
